using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WPF_UI.DTO
{
    public class MovieDto
    {
        /* Attributes */
        private int movieId;
        private string title;
        private int runtimeMinutes;
        private string director;
        private string production;
        private string synopsys;
        private string imagePath;
        private string premiereDate;
        private int year;
        //Foreign
        private int seasonId;
        private int filmGenreId;
        private string season;
        private string filmGenre;


        /*   */
        public int MovieId
        {
            get { return this.movieId; }

            set { this.movieId = value; }
        }
        public string Title
        {
            get { return this.title; }

            set { this.title = value; }
        }
        public int RuntimeMinutes
        {
            get { return this.runtimeMinutes; }

            set { this.runtimeMinutes = value; }
        }
        public string Director
        {
            get { return this.director; }

            set { this.director = value; }
        }
        public string Production
        {
            get { return this.production; }

            set { this.production = value; }
        }
        public string Synopsys
        {
            get { return this.synopsys; }

            set { this.synopsys = value; }
        }
        public string ImagePath
        {
            get { return this.imagePath; }

            set { this.imagePath = value; }
        }
        public string PremiereDate
        {
            get { return this.premiereDate; }

            set { this.premiereDate = value; }
        }
        public int Year
        {
            get { return this.year; }

            set { this.year = value; }
        }
        public int SeasonId
        {
            get { return this.seasonId; }

            set { this.seasonId = value; }
        }
        public int FilmGenreId
        {
            get { return this.filmGenreId; }

            set { this.filmGenreId = value; }
        }

        public string Season
        {
            get { return this.season; }

            set { this.season = value; }
        }

        public string FilmGenre
        {
            get { return this.filmGenre; }

            set { this.filmGenre = value; }
        }

        public MovieDto()
        {

        }

        // Constructor with movieId used for fetching All the movies from the Database (SELECT Statement)
        // Note: season is string here, because we can get the values such as ("Fall", "Winter" etc.) from the INNER JOIN
        public MovieDto(int movieId, string title, int runtimeMinutes, string director, string production, string synopsys, string imagePath, string premiereDate, string season, string filmGenre, int seasonId, int filmGenreId)
        {
            this.movieId = movieId;
            this.title = title;
            this.runtimeMinutes = runtimeMinutes;
            this.director = director;
            this.production = production;
            this.synopsys = synopsys;
            this.imagePath = imagePath;
            this.premiereDate = premiereDate;
            this.season = season;
            this.filmGenre = filmGenre;
            this.seasonId = seasonId;
            this.filmGenreId = filmGenreId;
        }

        // Constructor without movieId used for INSERT since movieId will be autogenerated
        // Note: season is int here, because we can need to INSERT  a FK of type int for Season
        public MovieDto(string title, int runtimeMinutes, string director, string production, string synopsys, string imagePath, string premiereDate, int season_Id, int filmgenre_id)
        {
            
            this.title = title;
            this.runtimeMinutes = runtimeMinutes;
            this.director = director;
            this.production = production;
            this.synopsys = synopsys;
            this.imagePath = imagePath;
            this.premiereDate = premiereDate;
            this.seasonId = season_Id;
            this.filmGenreId = filmgenre_id;
        }

        // Constructor with movieId used for UPDATE 
        // Note: seasonId is int here, because we can need to UPDATE a FK of type int for Season
        // Note: fimgenreId is int here, because we can need to UPDATE a FK of type int for FilmGenre
        public MovieDto(int movieId, string title, int runtimeMinutes, string director, string production, string synopsys, string imagePath, string premiereDate, int season_Id, int filmgenre_id)
        {
            this.movieId = movieId;
            this.title = title;
            this.runtimeMinutes = runtimeMinutes;
            this.director = director;
            this.production = production;
            this.synopsys = synopsys;
            this.imagePath = imagePath;
            this.premiereDate = premiereDate;
            this.seasonId = season_Id;
            this.filmGenreId = filmgenre_id;
        }

        public override string ToString()
        {
            //return base.ToString();
            return $"[movieId: "+this.movieId + ", title: " + this.title + ", year: "+this.year+"]";
        }
    }
}
